# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
