# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20160929_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
