# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('board', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('course', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
